services:

  db:
    image: mysql:8.0  # MySQL image
    container_name: mysql_erecipe
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=eRecipe  # Initial database
      - MYSQL_USER=django  # Custom user
      - MYSQL_PASSWORD=CHANGEME # Password for custom user
    ports:
      - "32770:3306"  # Expose port 3306 for MySQL
    volumes:
      - mysql_data:/var/lib/mysql  # Volume to persist data
  
  backend:
    build:
      context: ./server  # Path to your Django project
      dockerfile: Dockerfile  # Dockerfile used for building the Django container
    container_name: django_container
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - CORS_ALLOWED_ORIGINS=http://localhost:81,http://127.0.0.1:81
      - MYSQL=1
      - DB_NAME=eRecipe
      - USER=django
      - PWD=CHANGME
      - DB_HOST=192.168.0.226
      - DB_PORT=32770
    ports:
      - "80:8000"  # Expose port 8000 for Django
    depends_on:
      - db  # Ensure backend starts after the db container

  frontend:
    build:
      context: ./client  # Path to your React/Vite project
      dockerfile: Dockerfile  # Dockerfile used for building the frontend container
    container_name: react_frontend_container
    environment:
      - VITE_DOMAIN=http://127.0.0.1:80  # Environment variable for the frontend to know the backend URL
    ports:
      - "81:80"  # Expose port 80 for users to access the frontend
    depends_on:
      - backend

volumes:
  mysql_data:
