version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: django_container
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - CORS_ALLOWED_ORIGINS=http://localhost:81,http://127.0.0.1:81,http://frontend
      - MYSQL=0
      - DB_NAME=erecipe
      - USER=django
      - PWD=CHANGEME
      - DB_HOST=db  # Use the service name for container networking
      - DB_PORT=3306  # Make sure this matches the MySQL internal port
    ports:
      - "80:8000"  # Expose port 8000 for Django

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_DOMAIN: http://127.0.0.1:80  # Set VITE_DOMAIN as a build argument for Vite
    container_name: react_frontend_container
    ports:
      - "81:80"  # Expose port 80 for users to access the frontend
    depends_on:
      - backend

volumes:
  mysql_data:
