name: Docker Build, Test, and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Gitea Docker registry
        run: echo "${{ secrets.GITEA_TOKEN }}" | docker login gitea.home.sdtechlabs.com -u ${{ secrets.GITEA_USERNAME }} --password-stdin

      - name: Build Docker image with caching
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: gitea.home.sdtechlabs.com/${{ secrets.GITEA_USERNAME }}/erecipe:${{ github.sha }}
          cache-from: type=registry,ref=gitea.home.sdtechlabs.com/${{ secrets.GITEA_USERNAME }}/erecipe:latest
          cache-to: type=inline

      - name: Run Django tests
        run: |
          docker run --rm gitea.home.sdtechlabs.com/${{ secrets.GITEA_USERNAME }}/erecipe:${{ github.sha }} python server/manage.py test

      - name: Push Docker image to Gitea registry
        if: ${{ success() }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: gitea.home.sdtechlabs.com/${{ secrets.GITEA_USERNAME }}/erecipe:${{ github.sha }}

      - name: Notify on failure
        if: ${{ failure() }}
        run: echo "Docker build or tests failed. Please check the logs."
