name: Docker Build, Test, and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image but do not push yet
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server/
          push: false
          tags: edesign:${{ github.sha }}

      # Step 5: Log in to Gitea Docker registry (only if tests pass)
      - name: Log in to Gitea Docker registry
        if: ${{ success() }}
        run: echo "${{ secrets.GITEA_TOKEN }}" | docker login gitea.home.sdtechlabs.com -u ${{ secrets.GITEA_USERNAME }} --password-stdin

      # Step 6: Push Docker image to Gitea registry (only if tests pass)
      - name: Push Docker image to Gitea registry
        if: ${{ success() }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: gitea.home.sdtechlabs.com/${{ secrets.GITEA_USERNAME }}/edesign:${{ github.sha }}

      # Step 7: Notify if there's a failure
      - name: Notify on failure
        if: ${{ failure() }}
        run: echo "Docker build or tests failed. Please check the logs."
