name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      -main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Gitea Docker registry
      - name: Log in to Gitea Docker registry
        run: echo "${{ secrets.GITEA_TOKEN }}" | docker login gitea.home.sdtechlabs.com -u ${{ secrets.GITEA_USERNAME }} --password-stdin

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server/  # Use current directory as the context
          push: true  # Push the built image to the registry
          tags: gitea.home.sdtechlabs.com/${{ secrets.GITEA_USERNAME }}/erecipe_backend:latest  # Tag the image with 'latest'
